### PR TITLE
Add LDADD flag

### LINKED ISSUE #156: Installation on osx-arm64
I am trying to install NaMaster from source on an Apple Silicon machine. I found from conda-forge that osx-arm64 support is not available. Running `pip install .`, I get error on dependencies. I had linked the `chealpix` and the healpix included `libsharp` to the `_deps\lib` and `_deps\include` subfolders, but dependencies are still failing. GSL, FFTW and cfitsio are all installed via `brew` and included in `PATH`. 

Full error:
`Building wheels for collected packages: pymaster
  Building wheel for pymaster (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [93 lines of output]
      running bdist_wheel
      running build
      running build_py
      Found automake.
      configure.ac:23: warning: AC_PROG_CC_C99 is obsolete; use AC_PROG_CC
      configure.ac:26: warning: ac_ext=c
      configure.ac:26: ac_cpp='$CPP $CPPFLAGS'
      configure.ac:26: ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
      configure.ac:26: ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
      configure.ac:26: ac_compiler_gnu=$ac_cv_c_compiler_gnu
      configure.ac:26: if test -n "$ac_tool_prefix"; then
      configure.ac:26:   # Extract the first word of "${ac_tool_prefix}gcc", so it can be a program name with args.
      configure.ac:26: set dummy ${ac_tool_prefix}gcc; ac_word=$2
      configure.ac:26: { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
      configure.ac:26: printf %s "checking for $ac_word... " >&6; }
      configure.ac:26: if test ${ac_cv_prog_CC+y}
      configure.ac:26: then :
      configure.ac:26:   printf %s "(cached) " >&6
      configure.ac:26: else $as_nop
      configure.ac:26:   if test -n "$CC"; then
      configure.ac:26:   ac_cv_prog_CC="$CC" # Let the user override the test.
      configure.ac:26: else
      configure.ac:26: as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
      configure.ac:26: for as_dir in $PATH
      configure.ac:26: do
      configure.ac:26:   IFS=$as_save_IFS
      configure.ac:26:   case $as_dir in #(((
      configure.ac:26:     '' is m4_require'd but not m4_defun'd
      lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
      lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
      ./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
      ./lib/autoconf/programs.m4:41: _AC_CHECK_PROG is expanded from...
      ./lib/autoconf/programs.m4:101: AC_CHECK_PROG is expanded from...
      ./lib/autoconf/programs.m4:221: AC_CHECK_TOOL is expanded from...
      ./lib/autoconf/c.m4:452: AC_PROG_CC is expanded from...
      configure.ac:26: the top level
      configure.ac:32: error: possibly undefined macro: AC_PROG_LIBTOOL
            If this token and others are legitimate, please use m4_pattern_allow.
            See the Autoconf documentation.
      autoreconf: error: /opt/homebrew/Cellar/autoconf/2.71/bin/autoconf failed with exit status: 1
      Using -march=native. Binary will not be portable.
      configure: WARNING: unrecognized options: --enable-shared, --with-pic
      checking for a BSD-compatible install... /usr/bin/install -c
      checking whether build environment is sane... yes
      checking for a race-free mkdir -p... ./../../install-sh -c -d
      checking for gawk... no
      checking for mawk... no
      checking for nawk... no
      checking for awk... awk
      checking whether make sets $(MAKE)... yes
      checking whether make supports nested variables... yes
      checking whether to enable maintainer-specific portions of Makefiles... yes
      checking whether make supports the include directive... yes (GNU style)
      checking for arm64-apple-darwin20.0.0-gcc... arm64-apple-darwin20.0.0-clang
      checking whether the C compiler works... no
      configure: error: in `/Users/shamik/opt/NaMaster/_deps/libsharp2':
      configure: error: C compiler cannot create executables
      See `config.log' for more details
      make: *** No targets specified and no makefile found.  Stop.
      make: *** No rule to make target `install'.  Stop.
      cp: directory ../include/libsharp2 does not exist
      checking for a BSD-compatible install... /usr/bin/install -c
      checking whether build environment is sane... yes
      checking for a thread-safe mkdir -p... ./install-sh -c -d
      checking for gawk... no
      checking for mawk... no
      checking for nawk... no
      checking for awk... awk
      checking whether make sets $(MAKE)... yes
      checking whether make supports nested variables... yes
      checking for style of include used by make... GNU
      checking for arm64-apple-darwin20.0.0-gcc... arm64-apple-darwin20.0.0-clang
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether we are using the GNU C compiler... yes
      checking whether arm64-apple-darwin20.0.0-clang accepts -g... yes
      checking for arm64-apple-darwin20.0.0-clang option to accept ISO C89... none needed
      checking whether arm64-apple-darwin20.0.0-clang understands -c and -o together... yes
      checking dependency style of arm64-apple-darwin20.0.0-clang... gcc3
      checking for arm64-apple-darwin20.0.0-ar... arm64-apple-darwin20.0.0-ar
      checking the archiver (arm64-apple-darwin20.0.0-ar) interface... ar
      checking build system type... Invalid configuration `arm64-apple-darwin20.0.0': machine `arm64-apple' not recognized
      configure: error: /bin/sh ./config.sub arm64-apple-darwin20.0.0 failed
      ERROR: failed to configure libnmt. Check all dependencies are installed
             Dependencies:
             - GSL
             - FFTW
             - CFITSIO
             - HEALPix
      error: Failed to compile C library.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pymaster
  Running setup.py clean for pymaster
Failed to build pymaster
Installing collected packages: pymaster
  Running setup.py install for pymaster ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pymaster did not run successfully.
  │ exit code: 1
  ╰─> [97 lines of output]
      running install
      /Users/shamik/miniforge3/envs/arm/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      Found automake.
      configure.ac:23: warning: AC_PROG_CC_C99 is obsolete; use AC_PROG_CC
      configure.ac:26: warning: ac_ext=c
      configure.ac:26: ac_cpp='$CPP $CPPFLAGS'
      configure.ac:26: ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
      configure.ac:26: ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
      configure.ac:26: ac_compiler_gnu=$ac_cv_c_compiler_gnu
      configure.ac:26: if test -n "$ac_tool_prefix"; then
      configure.ac:26:   # Extract the first word of "${ac_tool_prefix}gcc", so it can be a program name with args.
      configure.ac:26: set dummy ${ac_tool_prefix}gcc; ac_word=$2
      configure.ac:26: { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
      configure.ac:26: printf %s "checking for $ac_word... " >&6; }
      configure.ac:26: if test ${ac_cv_prog_CC+y}
      configure.ac:26: then :
      configure.ac:26:   printf %s "(cached) " >&6
      configure.ac:26: else $as_nop
      configure.ac:26:   if test -n "$CC"; then
      configure.ac:26:   ac_cv_prog_CC="$CC" # Let the user override the test.
      configure.ac:26: else
      configure.ac:26: as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
      configure.ac:26: for as_dir in $PATH
      configure.ac:26: do
      configure.ac:26:   IFS=$as_save_IFS
      configure.ac:26:   case $as_dir in #(((
      configure.ac:26:     '' is m4_require'd but not m4_defun'd
      lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
      lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
      ./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
      ./lib/autoconf/programs.m4:41: _AC_CHECK_PROG is expanded from...
      ./lib/autoconf/programs.m4:101: AC_CHECK_PROG is expanded from...
      ./lib/autoconf/programs.m4:221: AC_CHECK_TOOL is expanded from...
      ./lib/autoconf/c.m4:452: AC_PROG_CC is expanded from...
      configure.ac:26: the top level
      Makefile.am:3: error: Libtool library used but 'LIBTOOL' is undefined
      Makefile.am:3:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
      Makefile.am:3:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
      Makefile.am:3:   If 'LT_INIT' is in 'configure.ac', make sure
      Makefile.am:3:   its definition is in aclocal's search path.
      autoreconf: error: automake failed with exit status: 1
      Using -march=native. Binary will not be portable.
      configure: WARNING: unrecognized options: --enable-shared, --with-pic
      checking for a BSD-compatible install... /usr/bin/install -c
      checking whether build environment is sane... yes
      checking for a race-free mkdir -p... ./../../install-sh -c -d
      checking for gawk... no
      checking for mawk... no
      checking for nawk... no
      checking for awk... awk
      checking whether make sets $(MAKE)... yes
      checking whether make supports nested variables... yes
      checking whether to enable maintainer-specific portions of Makefiles... yes
      checking whether make supports the include directive... yes (GNU style)
      checking for arm64-apple-darwin20.0.0-gcc... arm64-apple-darwin20.0.0-clang
      checking whether the C compiler works... no
      configure: error: in `/Users/shamik/opt/NaMaster/_deps/libsharp2':
      configure: error: C compiler cannot create executables
      See `config.log' for more details
      make: *** No targets specified and no makefile found.  Stop.
      make: *** No rule to make target `install'.  Stop.
      cp: directory ../include/libsharp2 does not exist
      checking for a BSD-compatible install... /usr/bin/install -c
      checking whether build environment is sane... yes
      checking for a thread-safe mkdir -p... ./install-sh -c -d
      checking for gawk... no
      checking for mawk... no
      checking for nawk... no
      checking for awk... awk
      checking whether make sets $(MAKE)... yes
      checking whether make supports nested variables... yes
      checking for style of include used by make... GNU
      checking for arm64-apple-darwin20.0.0-gcc... arm64-apple-darwin20.0.0-clang
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether we are using the GNU C compiler... yes
      checking whether arm64-apple-darwin20.0.0-clang accepts -g... yes
      checking for arm64-apple-darwin20.0.0-clang option to accept ISO C89... none needed
      checking whether arm64-apple-darwin20.0.0-clang understands -c and -o together... yes
      checking dependency style of arm64-apple-darwin20.0.0-clang... gcc3
      checking for arm64-apple-darwin20.0.0-ar... arm64-apple-darwin20.0.0-ar
      checking the archiver (arm64-apple-darwin20.0.0-ar) interface... ar
      checking build system type... Invalid configuration `arm64-apple-darwin20.0.0': machine `arm64-apple' not recognized
      configure: error: /bin/sh ./config.sub arm64-apple-darwin20.0.0 failed
      ERROR: failed to configure libnmt. Check all dependencies are installed
             Dependencies:
             - GSL
             - FFTW
             - CFITSIO
             - HEALPix
      error: Failed to compile C library.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pymaster

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.`

### PR DESCRIPTION
**Pull request by xgarrido**
This makes sure the library is built first and then the `namaster` bin program. 

This should (partially) fixed #156 but one needs to rebuild all configuration files with `autoreconf -ivf` (and thus update all the config*, depcomp... files available in this repository). This is needed by libtool 2.4.7 (as explained in #156 but this is also true for recent linux boxes) but I don't know how backward compatible it is.

Reference https://www.gnu.org/software/automake/manual/automake.html#Libtool-Libraries

Tested on linux OS and Mac OS.

### CODE REVIEW

**Comment by damonge** [comment]
@xgarrido sorry for the delay. Happy this works, but one needs to rerun autoreconf, right?
I don't think I can do that from your fork, so either you do it or I copy these changes into my own branch. How would you like to proceed?

**Comment by xgarrido** [comment]
I actually think that the different generated files are very machine dependent. I think a better way is to run `autoreconf -ivf` within the `scripts/install_libnmt.sh` (before the `configure` line) to make sure the `configure` stuff are generated by the machine itself and its autotools. Otherwise you will get incompatible files (for instance, I have regenerated the files with libtool 2.4.7 and I got an error on ubuntu 20.04 which is running libtool 2.4.6). This implies that the autotools are available but, in any case, you need them for building `libsharp`, so it's a prerequisite.

My advice would be to do what you actually do for `libsharp` i.e. add a `autoreconf -ivf` line in `scripts/install_libnmt.sh` and also remove every auto-generated files in this repository (as it is done in libsharp repository https://gitlab.mpcdf.mpg.de/mtr/libsharp, see also https://stackoverflow.com/questions/3290908/which-files-generated-by-autotools-should-i-keep-in-version-control-repository). I think it will be saner and safer.

**Comment by damonge** [comment]
That's a shame, since this is precisely what autotools was meant to solve. But I see your point that libsharp already requires it.
OK, so, in response to my previous question: are you happy for me to do this in a different branch and then we close this PR, or would you rather do this here?

**Review by damonge — APPROVED** [review]

**Comment by damonge** [comment]
Sounds good. Let's wait for the tests to pass and I'll merge it.

**Comment by damonge** [comment]
@xgarrido thanks a lot. Feel free to open the second PR whenever you get a chance (or tell me to do it!)

**Pull request merged**
