### PR TITLE
Travis mac

### PR DESCRIPTION
**Pull request by fjaviersanchez**
this solves #22. The test no. 41 is sometimes failing for Mac OS X in Travis for some reason.

### CODE REVIEW

**Comment by damonge** [comment]
@fjaviersanchez can you check what's happening here? It seems like the MAC builds are stalling or something like that.

**Comment by fjaviersanchez** [comment]
@damonge: For the OSX tests I decided to install gcc (rather than using clang) so we are able to check the openmp functionalities (and since this is what I was doing previously, I decided to make the minimal perturbation). However, now I can use the default clang (disabling openmp) and/or use the conda-forge package from @beckermr. The problem that I was having is that brew was stalling in the xcode8 environment in Travis for some unclear reason, I changed the environment and this seems to be solved. Please, let me know if you want me to change something else here.

**Comment by fjaviersanchez** [comment]
@damonge: Good news is that it runs. Bad news is that for python-3.7 some of the tests fail:

```
test_mask_c1 (test.test_nmt_utils.TestUtilsMaskSph) ... FAIL
test_mask_c2 (test.test_nmt_utils.TestUtilsMaskSph) ... FAIL
test_mask_errors (test.test_nmt_utils.TestUtilsMaskSph) ... ok
test_synfast_flat_errors (test.test_nmt_utils.TestUtilsSynfastFsk) ... ok
test_synfast_flat_stats (test.test_nmt_utils.TestUtilsSynfastFsk) ... FAIL
test_synfast_errors (test.test_nmt_utils.TestUtilsSynfastSph) ... ok
test_synfast_stats (test.test_nmt_utils.TestUtilsSynfastSph) ... FAIL
======================================================================
FAIL: test_mask_c1 (test.test_nmt_utils.TestUtilsMaskSph)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/build/LSSTDESC/NaMaster/test/test_nmt_utils.py", line 215, in test_mask_c1
    self.assertTrue((np.fabs(msk_apo[self.th<self.th0-np.radians(self.aposize)]-1.)<1E-10).all())
AssertionError: False is not true
======================================================================
FAIL: test_mask_c2 (test.test_nmt_utils.TestUtilsMaskSph)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/build/LSSTDESC/NaMaster/test/test_nmt_utils.py", line 227, in test_mask_c2
    self.assertTrue((np.fabs(msk_apo[self.th<self.th0-np.radians(self.aposize)]-1.)<1E-10).all())
AssertionError: False is not true
======================================================================
FAIL: test_synfast_flat_stats (test.test_nmt_utils.TestUtilsSynfastFsk)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/build/LSSTDESC/NaMaster/test/test_nmt_utils.py", line 114, in test_synfast_flat_stats
    self.assertTrue(get_diff(ctt1,self.cltt,self.cltt,self.cltt,self.cltt,nk).all())
AssertionError: False is not true
======================================================================
FAIL: test_synfast_stats (test.test_nmt_utils.TestUtilsSynfastSph)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/build/LSSTDESC/NaMaster/test/test_nmt_utils.py", line 179, in test_synfast_stats
    self.assertTrue(get_diff(ctt1,self.cltt,self.cltt,self.cltt,self.cltt).all())
AssertionError: False is not true
----------------------------------------------------------------------
Ran 48 tests in 93.744s```

**Comment by fjaviersanchez** [comment]
I think this is deprecated so, I'll close and will open a new PR if relevant.

**Pull request closed without merging**
