### PR TITLE
PR to track typos directly in the paper

### PR DESCRIPTION
**Pull request by EiffL**
I'm opening this PR to directly fix some minor typos I've found in the draft. I figured this was more efficient than commenting on them in the review on confluence. Don't merge just yet, I might still find some other minor things tonight as I'm finishing my review.

### CODE REVIEW

**Comment by damonge** [comment]
Cool, thanks! You'll see that the draft has changed a bit, side we've started addressing Boris' and Scott's comments.

**Comment by EiffL** [comment]
I haven't found any other typos, I think that's it :-) Feel free to merge if you agree with my proposed corrections.

**Comment by damonge** [comment]
Hey @EiffL : sorry I was an idiot. I thought you had pointed this PR to our master branch, which has an outdated version of the paper, so I implemented your modifications by hand in our paper_response branch. Now I realize you had actually pointed to the correct branch, but my modifications have caused an obvious conflict.

Are you OK with scrapping this PR, since the modifications you've made are already implemented in the paper?

**Comment by EiffL** [comment]
No worries :-) I'm closing it.

**Pull request closed without merging**
